#BSUB -n 4
#BSUB -e /gpfs/data/denizlab/Users/bz1030/KneeNet/KneeProject/model/model_torch/model_flatten_linear_layer/evaluate%J.err
#BSUB -o /gpfs/data/denizlab/Users/bz1030/KneeNet/KneeProject/model/model_torch/model_flatten_linear_layer/evaluate%J.out
#BSUB -gpu "num=1:mode=shared:j_exclusive=yes"
#BSUB -q short

. /gpfs/share/skynet/apps/anaconda3/etc/profile.d/conda.sh
conda activate powerai1.6_env
python /gpfs/data/denizlab/Users/bz1030/KneeNet/KneeProject/model/model_torch/model_flatten_linear_layer/evaluate.py --model 3